#include "tx.h"
#include "adc.h"
#include "drv_uart.h"
#include "platform.h"

static void setup_pin_SYNC_TX(void);

void tx_init(void)
{
    // Set up pin which triggers ISR
    setup_pin_SYNC_TX();
}

// Called every edge on SYNC_TX pin.
//
// AMDC uses this signal to tell motherboard when
// to send ADC sample data back to AMDC.
//
// NOTE: this ISR has the highest priority on the
// system. It will preempt the ADC conversions.
void EXTI15_10_IRQHandler(void)
{
    // Clear interrupt
    if (__HAL_GPIO_EXTI_GET_IT(GPIO_PIN_11)) {
        __HAL_GPIO_EXTI_CLEAR_IT(GPIO_PIN_11);
    }

    // Get latest data from ADC driver (non-blocking)
    uint16_t bits[8];
    adc_latest_bits(bits);

    // Send data out over UART
    for (int uart_pin = 0; uart_pin < 2; uart_pin++) {
        uint8_t uart_data[12];
        for (int i = 0; i < 4; i++) {
            uint16_t sample = bits[(4 * uart_pin) + i];

            // Send header as:
            // bits[7:2] = 100100
            // bits[1:0] = # of DC (2 bits, 0..3)
            uint8_t header = 0x90;
            header |= (0x03 & i);

            uart_data[(3 * i) + 0] = header;
            uart_data[(3 * i) + 1] = (uint8_t)(sample >> 8);
            uart_data[(3 * i) + 2] = (uint8_t)(sample & 0x00FF);
        }

        drv_uart_send(uart_pin + 1, uart_data, 12);
    }
}

static void setup_pin_SYNC_TX(void)
{
    // TX Sync is a square wave input where every edge should
    // trigger the transmission of the motherboard ADC samples
    // back to the AMDC.
    //
    // These edges are generated by the user's code on the AMDC,
    // so there are no guarantees on timing or frequency of transmission.

    GPIO_InitTypeDef GPIO_InitStruct = { 0 };

    __HAL_RCC_GPIOB_CLK_ENABLE();

    // Configure GPIO pin Output Level
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET);

    // Configure GPIO pins
    GPIO_InitStruct.Pin = GPIO_PIN_11;
    GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING_FALLING;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // EXTI interrupt init
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}
