#include "tx.h"
#include "adc.h"
#include "drv_uart.h"
#include "platform.h"

static void setup_pin_SYNC_TX(void);

void tx_init(void)
{
    // Set up pin which triggers ISR
    setup_pin_SYNC_TX();
}

// Called every edge on SYNC_TX pin.
//
// AMDC uses this signal to tell motherboard when
// to send ADC sample data back to AMDC.
//
// NOTE: this ISR has the highest priority on the
// system. It will preempt the ADC conversions.
void EXTI15_10_IRQHandler(void)
{
    // Clear interrupt
    if (__HAL_GPIO_EXTI_GET_IT(GPIO_PIN_11)) {
        __HAL_GPIO_EXTI_CLEAR_IT(GPIO_PIN_11);
    }

    // Tell ADC driver to throw away next sample it gets
    // since this ISR messed up alignment to PWM carrier
    // and will add noise!
    adc_ignore_next_sample();

    // Send header before we compute anything
    // to get the UART warmed up and running!
    uint8_t first_header = 0x90;
    drv_uart_putc_fast(USART2, first_header);
    drv_uart_putc_fast(USART3, first_header);

    // Get latest data from ADC driver (non-blocking)
    uint16_t bits[8];
    adc_latest_bits(bits);

    // Send data out over UART
    for (int i = 0; i < 4; i++) {
        uint16_t sample1 = bits[(4 * 0) + i];
        uint16_t sample2 = bits[(4 * 1) + i];

        // Send header as:
        // bits[7:2] = 100100
        // bits[1:0] = # of DC (2 bits, 0..3)
        uint8_t header = 0x90;
        header |= (0x03 & i);

        // Send header (not the first one)
        if (i > 0) {
            drv_uart_putc_fast(USART2, header);
            drv_uart_putc_fast(USART3, header);
        }

        // Send ADC sample data MSBs
        drv_uart_putc_fast(USART2, (uint8_t)(sample1 >> 8));
        drv_uart_putc_fast(USART3, (uint8_t)(sample2 >> 8));

        // Send ADC sample data LSBs
        drv_uart_putc_fast(USART2, (uint8_t)(sample1 & 0x00FF));
        drv_uart_putc_fast(USART3, (uint8_t)(sample2 & 0x00FF));
    }

    // Wait for entire UART transmission to complete
    drv_uart_wait_TC(USART2);
    drv_uart_wait_TC(USART3);
}

static void setup_pin_SYNC_TX(void)
{
    // TX Sync is a square wave input where every edge should
    // trigger the transmission of the motherboard ADC samples
    // back to the AMDC.
    //
    // These edges are generated by the user's code on the AMDC,
    // so there are no guarantees on timing or frequency of transmission.

    GPIO_InitTypeDef GPIO_InitStruct = { 0 };

    __HAL_RCC_GPIOB_CLK_ENABLE();

    // Configure GPIO pin Output Level
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, GPIO_PIN_RESET);

    // Configure GPIO pins
    GPIO_InitStruct.Pin = GPIO_PIN_11;
    GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING_FALLING;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    // EXTI interrupt init
    HAL_NVIC_SetPriority(EXTI15_10_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}
